name: "\U0001F41E Bug report"
description: Create a report to help us improve
labels: [bug]
assignees: jeremyfrank
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what the expected behavior is.
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to where the bug can be reproduced.
      placeholder: Reproduction URL
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described.
      placeholder: Go to ___, click on ___, scroll down to ___, see the error.
  - type: textarea
    id: device-browser-info
    attributes:
      label: Device and browser info
      description: OS, Device, Browser, Version
      value: |
        - OS:
        - Browser:
        - Version:
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
